### ISSUE TITLE
How does login work

### ISSUE THREAD

**Issue by el-davo** [yahoohung/loopback-graphql-server#2]
Hi thanks for creating this lib, it works great. Im confused about a few things though. Firstly how does someone login. I have tried with the graphql query below

```
mutation {
  userLogin(input: {credentials: {username:"test", password:"test"}}) {
    obj
  }
}
```

However this gives the error response 

```
{
  "data": {
    "userLogin": null
  },
  "errors": [
    {
      "message": "include.toLowerCase is not a function",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "userLogin"
      ]
    }
  ]
}
```

Secondly, after logging in and getting my access token, how do i then use that access token to query models?

I am using loopback3 btw. Any help appreciated

**Comment by Thyvo** [comment]
Hi el-davo,

I ran into the same issue and did some investigation.
i found out that this error is due to and undefined variable that is being assigned to the include variable on line 65 of src/schema/mutation/getRemoteMethodMutations.js
I resolved this by applying the work around below.

Work arround:
replace
`Line 65: let ctxOptions = { accessToken: context.req.accessToken }`
with 
```
let ctxOptions;
if(model.modelName == "user" && method.name == "login"){
  let ctxOptions = "";
}else{
  let ctxOptions = { accessToken: context.req.accessToken }
}
```

I know this is not a proper fix but this was the best fix I was able to think of as a starter/novice with loopback and Node.js but maybe this will help the author of this package to apply a proper fix.

Kind regards,
Thyvo

**Comment by el-davo** [comment]
Hi @Thyvo, nice work. I’ll take a look at your suggested fix when I get the chance. Thanks again

**Comment by yahoohung** [comment]
Thanks @Thyvo

**Comment by sskhokhar** [comment]
This is not fixed. I installed latest version of module and checked that these lines are present in the file but still facing this error on custom user model.

**Comment by ColinKrist** [comment]
@yahoohung I also am facing this issue. How can we make it possible for us to define our own custom user model into the fix? Also the default user model has a capital U now which breaks this lib too.
